qr/urls.py
from django.urls import path
from .views import home, login_view, signup
app_name = 'qr'
urlpatterns = [
    path("home/", home, name="home"),
    path('login/', login_view, name="login"),
    path('signup/', signup, name="signup"),
]

qrcodegen/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("qr/", include("qr.urls")),
]

qr/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
# Create your models here.


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email = models.EmailField(max_length=254)

    def __str__(self):
        return f'{self.user.first_name} {self.user.last_name} {self.user.email}'

qr/views.py
import json
import os

from django.core.cache import cache
from django.shortcuts import render, redirect
from django.utils.crypto import get_random_string
from django.contrib.auth import authenticate, login
from django.http import HttpResponse
from .models import User, UserProfile


import qrcode
import qrcodegen

# Create your views here.


qr = qrcode.QRCode(
    version=1,
    error_correction=qrcode.constants.ERROR_CORRECT_H,
    box_size=10,
    border=4,
)


def home(request):
    context = {}
    if request.method == "POST":
        name = request.POST.get('name')
        details = request.POST.get('details')
        context.update({
            "name": name,
            "details": details
        })
        print(context)
        data = json.dumps(context)

        qr.add_data(data)
        qr.make(fit=True)
        image = qr.make_image(fill_color="black", back_color="white")
        img_name = get_random_string(8)+".png"
        context.update({'qr_name': img_name})
        qr_path = os.path.join(qrcodegen.settings.BASE_DIR,
                               'static/images', img_name)
        qr_code_count = cache.get('qr_code_count', 0)
        qr_code_count += 1
        cache.set('qr_code_count', qr_code_count)
        context.update({'qr_code_count': qr_code_count})
        image.save(qr_path)
        print(context)
        return render(request, "qr/generate.html", context=context)
    else:
        error_message = 'Invalid details'
    return render(request, "qr/home.html", )


def login_view(request):
    cart = json.loads(request.COOKIES.get('cart', '{}'))
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        remember_me = request.POST.get('remember-me')
        user = authenticate(request, username=email, password=password)
        if user is not None:
            response = HttpResponse()
            response.delete_cookie('register')  # delete the cart cookie
            login(request, user)
            response = HttpResponse()
            # set a cookie that lasts for 30 days
            response.set_cookie('cart', json.dumps(cart),
                                max_age=3600 * 24 * 30)
            if remember_me:
                request.session.set_expiry(1209600)  # 2 weeks
            else:
                # session expires when user closes browser
                request.session.set_expiry(0)
            return redirect('qr:home')
        else:
            error_message = 'Invalid email or password'
    else:
        error_message = 'Invalid email or password'

    return render(request, "qr/login.html", {'error_message': error_message})


def signup(request):
    if request.method == 'POST':

        # form submission
        f_name = request.POST.get('name')
        e_mail = request.POST.get('email')
        password = request.POST.get('password')
        data = {"f_name": f_name,
                "e_mail": e_mail}
        print(f_name)
        print(password)
        if e_mail:
            user = User.objects.create_user(
                username=e_mail,
                password=password,  # set a default password here or let the user set it later
                email=e_mail,
            )
            user.save()
            print(user)
            user_profile = UserProfile.objects.create(
                user=user,
                email=e_mail,

            )
            user_profile.save()
            if request.user.is_authenticated:
                return redirect('qr:home')

        return redirect('home')

    return render(request, "qr/signup.html")

qr/templates/qr/generate.html
{% extends "base.html" %}{% load static %} {% block content %}
<style>
    .image-container {
        text-align: center;
    }
    .image-container img {
        max-width: 100%;
        max-height: 100%;
        display: block;
        margin: 0 auto;
        border: 4px solid #333; /* Dark border */
        padding: 10px; /* Add padding for spacing */
        box-sizing: border-box;
    }
    .scan-me-alert {
        font-weight: bold;
        font-size: 20px;
        background-color: blue;
        color: white;
        padding: 10px;
        margin: 0 auto;
        width: 200px;
    }
</style>

<div class="image-container">
    <img
        src="{% static '/images/'|add:qr_name %}"
        alt="QR Code"
        style="min-height: 400px; min-width: 400px"
    />
</div>
<div
    class="alert alert-primary text-center scan-me-alert"
    role="alert"
    style="text-align: center"
>
    SCAN ME
</div>
{% endblock %}

qr/templates/qr/home.html
{% extends "base.html" %} {% load static %}{% block content %}
<style>
    .container {
        display: flex;
        justify-content: center;
        margin-top: 20px;
    }

    .form-container {
        border: 1px solid #ccc;
        padding: 20px;
        border-radius: 5px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        width: 600px;
        background-color: #4c5d88;
    }
    .form-container h1,
    .form-container form label {
        color: #ffffff;
    }
    .form-container .form-group {
        margin-bottom: 15px;
    }
    .loading {
        display: none;
        text-align: center;
        margin-top: 20px;
    }
</style>

<div class="container">
    <div class="form-container">
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="name">Name:</label>
                <input
                    type="text"
                    class="form-control"
                    id="name"
                    placeholder="Enter your name"
                    name="name"
                />
            </div>
            <div class="form-group">
                <label for="details">Details:</label>
                <textarea
                    class="form-control"
                    id="details"
                    rows="3"
                    placeholder="Enter additional details"
                    name="details"
                ></textarea>
            </div>
            <div class="text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </form>
        <div class="loading">
            <div class="spinner-border text-primary" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
    </div>
</div>
<script>
    document
        .getElementById("myForm")
        .addEventListener("submit", function (event) {
            event.preventDefault();
            showLoadingAnimation();
            // Perform form submission or AJAX request here
            // Once the submission is complete, you can hide the loading animation
            // For demonstration purposes, we'll simulate a delay of 2 seconds before hiding the animation
            setTimeout(hideLoadingAnimation, 2000);
        });

    function showLoadingAnimation() {
        document.querySelector(".loading").style.display = "block";
    }

    function hideLoadingAnimation() {
        document.querySelector(".loading").style.display = "none";
    }
</script>

{% endblock %}

qr/templates/qr/login.html
{% extends "base.html" %}{% load static %} {% block content %}
<style>
    .login-container {
        background-color: #4c5d88;
        border: 1px solid #dddddd;
        border-radius: 5px;
        padding: 20px;
        margin-top: 50px;
    }

    .login-container h1 {
        text-align: center;
        margin-bottom: 20px;
        color: #ffffff;
    }

    .login-container form label {
        color: #ffffff;
    }

    .login-container form .form-control {
        margin-bottom: 15px;
    }

    .login-container form .btn-primary {
        background-color: #007bff;
        border-color: #007bff;
    }

    .login-container form .btn-primary:hover {
        background-color: #0069d9;
        border-color: #0069d9;
    }
</style>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-4 col-md-6 col-sm-8 login-container">
            <h1>Login</h1>
            <form method="POST" action="{% url 'qr:login' %}">
                {% csrf_token %}
                <div class="form-group">
                    <label for="email">Email Address</label>
                    <input
                        type="email"
                        class="form-control"
                        id="email"
                        placeholder="Enter your email address"
                        name="email"
                    />
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input
                        type="password"
                        class="form-control"
                        id="password"
                        placeholder="Enter your password"
                        name="password"
                    />
                </div>
                <div class="form-group form-check">
                    <input
                        type="checkbox"
                        class="form-check-input"
                        id="rememberMe"
                        name="remember-me"
                    />
                    <label class="form-check-label" for="rememberMe"
                        >Remember Me</label
                    >
                </div>
                <div class="text-center">
                    <button type="submit" class="btn btn-primary">Login</button>
                </div>
                <p>"{error_message}"</p>
            </form>
        </div>
    </div>
</div>
{% endblock %}

qr/templates/qr/signup.html
{% extends "base.html" %}{% load static %} {% block content %}
<style>
    .signup-container {
        background-color: #4c5d88;
        border: 1px solid #dddddd;
        border-radius: 5px;
        padding: 20px;
        margin-top: 50px;
    }
    .signup-container h1,
    .signup-container form label {
        color: #ffffff;
    }

    .signup-container h1 {
        text-align: center;
        margin-bottom: 20px;
    }
    .signup-container form .form-control {
        margin-bottom: 15px;
    }

    .signup-container form .form-group label {
        font-weight: bold;
    }

    .signup-container form .btn-primary {
        background-color: #007bff;
        border-color: #007bff;
    }

    .signup-container form .btn-primary:hover {
        background-color: #0069d9;
        border-color: #0069d9;
    }
    .signup-container form label {
        color: #ffffff;
    }
</style>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-4 col-md-6 col-sm-8 mb-2 signup-container">
            <form method="POST">
                <h1 style="font-color: #ffffff">Sign Up</h1>
                {% csrf_token %}
                <div class="form-group">
                    <label for="fullName">Full Name</label>
                    <input
                        type="text"
                        class="form-control"
                        id="fullName"
                        placeholder="Enter your full name"
                        name="name"
                    />
                </div>
                <div class="form-group">
                    <label for="email">Email Address</label>
                    <input
                        type="email"
                        class="form-control"
                        id="email"
                        placeholder="Enter your email address"
                        name="email"
                    />
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input
                        type="password"
                        class="form-control"
                        id="password"
                        placeholder="Enter a password"
                        name="password"
                    />
                </div>
                <div class="form-group">
                    <label for="confirmPassword">Confirm Password</label>
                    <input
                        type="password"
                        class="form-control"
                        id="confirmPassword"
                        placeholder="Confirm your password"
                    />
                </div>
                <div class="text-center">
                    <button
                        type="submit"
                        class="btn btn-primary btn-block text-center"
                    >
                        Sign Up
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <title>QR code Generator</title>
        <meta name="description" content="" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <!-- google font -->
        <link href="https://fonts.googleapis.com" rel="preconnect" />
        <link crossorigin href="https://fonts.gstatic.com" rel="preconnect" />
        <link
            href="https://fonts.googleapis.com/css2?family=Poppins&display=swap"
            rel="stylesheet"
        />

        <!-- fontawsome -->
        <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
            integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
            crossorigin="anonymous"
            referrerpolicy="no-referrer"
        />
        <!-- Bootstrap icons-->
        <link
            crossorigin="anonymous"
            href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.10.5/font/bootstrap-icons.min.css"
            integrity="sha512-ZnR2wlLbSbr8/c9AgLg3jQPAattCUImNsae6NHYnS9KrIwRdcY9DxFotXhNAKIKbAXlRnujIqUWoXXwqyFOeIQ=="
            referrerpolicy="no-referrer"
            rel="stylesheet"
        />
        <!-- bootstrap -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"></script>
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css"
            rel="stylesheet"
        />
        <link
            href="https://getbootstrap.com/docs/5.3/assets/css/docs.css"
            rel="stylesheet"
        />
        <script
            src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js"
            integrity="sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE"
            crossorigin="anonymous"
        ></script>
        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js"
            integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ"
            crossorigin="anonymous"
        ></script>
        <script
            crossorigin="anonymous"
            integrity="sha512-STof4xm1wgkfm7heWqFJVn58Hm3EtS31XFaagaa8VMReCXAkQnJZ+jEy8PCC/iT18dFy95WcExNHFTqLyp72eQ=="
            referrerpolicy="no-referrer"
            src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.3/jquery.min.js"
        ></script>
        <script
            crossorigin="anonymous"
            integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V"
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js"
        ></script>
        <link
            crossorigin="anonymous"
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
            integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
            rel="stylesheet"
        />
        <link
            crossorigin="anonymous"
            href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css"
            integrity="sha384-b6lVK+yci+bfDmaY1u0zE8YYJt0TZxLEAFyYSLHId4xoVvsrQu3INevFKo+Xir8e"
            rel="stylesheet"
        />
        <!-- style css -->
        <link href="{% static 'css/style.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!--load header here-->
        {% include 'includes/header.html' %}

        <!--load content here-->
        {% block content %}
        <!--content goes here-->
        {% endblock %}

        <!--load footer here-->
        {% include 'includes/footer.html' %}

        <script src="" async defer></script>
    </body>
</html>

templates/includes/header.html
{% load static %}

<style>
    #header_top {
        background-color: #4c5d88;
    }
    img {
        height: 45px;
        width: 220px;
    }

    .cart-icon {
        display: inline-block;
        position: relative;
        text-decoration: none;
        color: #000;
    }

    .cart-icon .bi {
        font-size: 1.5rem;
    }

    .cart-count {
        display: inline-block;
        position: absolute;
        top: -0.5rem;
        right: -0.5rem;
        min-width: 1rem;
        padding: 0.2rem;
        font-size: 0.8rem;
        font-weight: bold;
        color: #fff;
        background-color: #f00;
        border-radius: 50%;
        text-align: center;
    }

    .nav-item a {
        color: rgba(0, 0, 0, 0.55);
    }

    .nav-link:focus {
        outline: none;
    }

    .nav-item {
        padding: 5px;
        align-items: center;
        display: flex;
    }

    .search-btn {
        display: flex;
        align-items: center;
        gap: 0;
        width: 240px;
        height: 35px;
        line-height: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
        margin-left: 10zpx;
    }

    #search-input {
        border: none;
        outline: none;
        padding: 5px;
    }

    @media (max-width: 991px) {
        .nav-item {
            padding: 5px;
            align-items: center;
            display: flex;
            border-bottom: 1px solid #ccc;
        }
    }

    @media (min-width: 991px) {
        .navbar-nav {
            justify-contents: center;
            align-items: center;
        }
    }
</style>

<nav
    id="header_top"
    class="navbar navbar-expand-lg bg-body-tertiary"
    style="background-color: #4c5d88"
>
    <div class="container-fluid p-3">
        <a class="navbar-brand" href=""
            ><img alt="Couzy" src="{% static 'images/couzy.jpg' %}"
        /></a>
        <!--		<a class="navbar-brand" href="https://metabolomicscentre.ca/"><img alt="Metabolic" src="{% static 'img/metabolic.svg' %}"></a>-->
        <button
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation"
            class="navbar-toggler"
            data-bs-target="#navbarSupportedContent"
            data-bs-toggle="collapse"
            type="button"
        >
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0 d-flex">
                <li class="nav-item">
                    <a aria-current="page" class="nav-link active" href=""
                        >Home</a
                    >
                </li>
                <li class="nav-item">
                    <a class="nav-link" href=""> About </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="">Services</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'qr:login' %}"> Log In </a>
                </li>

                <li class="nav-item">
                    <a href="#" target="_blank"
                        ><i class="bi bi-linkedin"></i
                    ></a>
                </li>
                <li class="nav-item">
                    <a href="#" target="_blank"
                        ><i class="bi bi-twitter"></i
                    ></a>
                </li>

                <li class="nav-item">
                    <a href="#" target="_blank"
                        ><i class="bi bi-facebook"></i
                    ></a>
                </li>

                <li class="nav-item" id="cart-icon-placeholder"></li>
            </ul>
        </div>
    </div>
</nav>
<hr />

<script>
    $(function () {
        var cart = JSON.parse(getCookie("cart") || "{}");
        var count = Object.values(cart).reduce(
            (total, item) => total + item.quantity,
            0
        );
        if (count > 0) {
            $("#cart-icon-placeholder").html(
                '<a href="" class="cart-icon"><i class="bi bi-cart-fill"></i><span class="cart-count">' +
                    count +
                    "</span></a>"
            );
        }
    });

    function getCookie(name) {
        var match = document.cookie.match(
            new RegExp("(^| )" + name + "=([^;]+)")
        );
        if (match) {
            return decodeURIComponent(match[2]);
        }
        return null;
    }
</script>